package interfaces;

import java.io.Serializable;

/**
 * Represents a request for a new game session on the server or a request to join an existing game
 */
public class CreateJoinRequest implements Serializable {
    private String userName;
    private RequestType requestType;
    private int sessionId;

    public enum RequestType {
        JOIN,
        CREATE,
        PING
    }

    /**
     * Constructor to ping server for available games.
     */
    public CreateJoinRequest() {
        requestType = RequestType.PING;
    }

    /**
     * Constructor for a new game request. Id is not specified by the client. Rather, it is generated by server
     * @param userName Requesting client's username
     */
    public CreateJoinRequest(String userName) {
        this.userName = userName;
        this.requestType = RequestType.CREATE;
    }

    /**
     * Constructor for an on-going game join request. Id is of an existing game
     * @param userName Requesting client's username
     * @param sessionId Game id client wishes to join
     */
    public CreateJoinRequest(String userName, int sessionId) {
        this.userName = userName;
        this.requestType = RequestType.JOIN;
        this.sessionId = sessionId;
    }

    public RequestType type() {
        return requestType;
    }

    /**
     * @return Requesting client user name
     */
    public String getRequestingClientUserName() {
        return this.userName;
    }

    /**
     * @return True if this request is for a new game
     */
    public boolean isNewGame() {
        return requestType == RequestType.CREATE;
    }

    public int getSessionId() {
        return this.sessionId;
    }
}
