package interfaces;

/**
 * Represents a request for a new game session on the server
 */
public class NewUserRequest {
    private String userName;
    private boolean newGame;
    private int sessionId;

    /**
     * Constructor for a new game request. Id is not specified by the client. Rather, it is generated by server
     * @param userName Requesting client's username
     */
    public NewUserRequest(String userName) {
        this.userName = userName;
        this.newGame = true;
    }

    /**
     * Constructor for an on-going game join request. Id is of an existing game
     * @param userName Requesting client's username
     * @param sessionId Game id client wishes to join
     */
    public NewUserRequest(String userName, int sessionId) {
        this.userName = userName;
        this.newGame = false;
        this.sessionId = sessionId;
    }

    /**
     * @return Requesting client user name
     */
    public String getRequestingClientUserName() {
        return this.userName;
    }

    /**
     * @return True if this request is for a new game
     */
    public boolean isNewGame() {
        return this.newGame;
    }

    public int getSessionId() {
        return this.sessionId;
    }
}
